# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 11.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo web client UI related addons
repo_name: Odoo web client UI related addons
repo_slug: web
repo_website: https://github.com/OCA/web

