{
    "name": "Boolean Button Widget",
    "version": "13.0.1.0.0",
    "category": "Web",
    "summary": "Boolean Button Widget for Forms with legend",
    "license": "LGPL-3",
    "author": "Bigdata BY, Odoo SA, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/web",
    "depends": ["web"],
    "data": ["views/templates.xml"],
    "qweb": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
